name: Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@feature/conditional-ci
    secrets: inherit

  terraform-checks:
    name: Terraform
    uses: canonical/observability/.github/workflows/terraform-quality-checks.yaml@main